### ISSUE TITLE
Sprite de "enemigo" no encaja con su nombre

### ISSUE THREAD

**Issue by MarcosMD15** [CrunchesterStudio/LouseAttack#125]
- Prioridad: Impacto bajo.

- Plataforma: todas las plataformas.

- Descripción: Al intentar salir del juego pero cancelar la acción el sprite del "enemigo" cambia y ya no concuerda con su nombre.

- Pasos para reproducirlo:  
          1º - Abrir juego.
          2º - Pulsar botón "jugar".
          3º - Esperar a que la partida se guarde.
          4º - Pulsar botón "salir".
          5º - Pulsar botón "volver al juego".
          6º- El sprite del "enemigo" cambia y ya no concuerda con su nombre.

- Posible causa: Creemos que el fallo tiene que ver con el sistema de guardado de esa información en concreto.

![imagen 1](https://user-images.githubusercontent.com/55489396/143057987-5455cec4-83ac-42d4-a150-e2c2bca23e5d.PNG)
![imagen 2](https://user-images.githubusercontent.com/55489396/143058006-2cd296f1-2eb0-4630-928c-8f0cdd585e63.PNG)

**Comment by IvanSploy** [comment]
A nosotros nos ha ocurrido el mismo error.
