### ISSUE TITLE
El juego entra en un Loop infinito y crashea.

### ISSUE THREAD

**Issue by jvicog** [CrunchesterStudio/LouseAttack#128]
Prioridad: impacto crítico.

Descripción: dentro del juego se genera un loop infinito que corrompe WebGL. Desconozco el problema pero muy probablemente dentro del código se encuentre algún bucle en el que en ciertas condiciones, no pueda salir.

Plataforma: ordenador de la universidad, windows 10, modo incógnito en Chrome.

Pasos: Desconocidos. Sólo ha ocurrido una vez y no he encontrado la manera de replicarlo.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/63055692/143316414-b39ca61b-c875-4df2-89d6-0887bf92fc8f.png)

**Comment by JuanJesus5** [comment]
Nunca nos ha surgido este bug, tras todas las pruebas internas y externas. No hay forma de provocarlo y lo más probable es que haya sido producto de algún tipo de acción sobre el navegador externa al juego. Se sigue trabajando en su detección por si este fallo fuese realmente producto de nuestra aplicación.
