### ISSUE TITLE
El botón principal para conseguir más "piojos" es difícil de utilizar en dispositivos móviles

### ISSUE THREAD

**Issue by Javaperwave** [CrunchesterStudio/LouseAttack#137]
- Prioridad: impacto medio

- Plataforma: Android 

- Descripción: el botón situado abajo a la derecha que te permite adquirir más "piojos" tiene un tamaño reducido. Esto resulta en situaciones donde no se registran adecuadamente los clicks.

**Comment by JuanJesus5** [comment]
Se han realizado varias pruebas para aumentar el tamaño de dicho botón, pero, la usabilidad se ve empeorada así como la estética. 
Es una desventaja de los móviles con pantallas pequeñas respecto del resto de plataformas y tamaños, pero, el equipo considera que siempre existen diferentes versiones de los juegos acorde a la plataforma en la que se juegan y asume esa desventaja como aceptable para este tipo de dispositivos.

![Prueba1](https://user-images.githubusercontent.com/61622894/145685010-73667b83-e21a-49b8-94c8-7db1a83bb8ac.jpeg)
![Prueba2](https://user-images.githubusercontent.com/61622894/145685011-e94586e9-f2ab-4caf-af22-f468484fa510.jpeg)
